name: offline-3d-gis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - gdal>=3.10.3
  - libgdal-jp2openjpeg  # Explicitly required for raw .j2k codestream support
  - rasterio=1.4.3
  - pyproj
  - shapely=2.0.7
  - scipy
  - numpy
  - pip:
      - -e .[desktop,geo,dev]
