#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Build a fully offline Windows installer for Offline 3D GIS Desktop.

.DESCRIPTION
    Uses conda-pack to bundle the entire conda environment (Python + Qt + GDAL +
    all native libs) into a self-contained archive, then wraps it with NSIS to
    produce a single-file .exe installer.

    Requirements (run once on a Windows machine with conda):
        conda install -c conda-forge conda-pack nsis

.PARAMETER CondaEnvName
    Name of the conda environment to pack. Default: offline-3d-gis

.PARAMETER OutDir
    Directory where the installer .exe will be written. Default: dist\

.PARAMETER AppVersion
    Version string embedded in the installer. Default: 0.1.0

.EXAMPLE
    .\build_windows_installer.ps1
    .\build_windows_installer.ps1 -CondaEnvName offline-3d-gis -AppVersion 1.0.0
#>
param(
    [string]$CondaEnvName = "offline-3d-gis",
    [string]$OutDir       = "dist",
    [string]$AppVersion   = "0.1.0"
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Resolve-Path (Join-Path $ScriptDir "..")

Set-Location $RepoRoot

# ── Helpers ──────────────────────────────────────────────────────────────────
function Step([string]$msg, [scriptblock]$action) {
    Write-Host "`n==> $msg" -ForegroundColor Cyan
    & $action
    if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) {
        throw "Step failed ($LASTEXITCODE): $msg"
    }
}

function Require([string]$cmd) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "Required tool not found: $cmd  (install with: conda install -c conda-forge $cmd)"
    }
}

# ── Validate tools ────────────────────────────────────────────────────────────
Require "conda"
Require "conda-pack"
Require "makensis"

# ── Paths ─────────────────────────────────────────────────────────────────────
$PackedEnvArchive = Join-Path $RepoRoot "installer\offline-3d-gis-env.tar.gz"
$NsisScript       = Join-Path $RepoRoot "installer\offline_gis_installer.nsi"
$OutDirFull       = Join-Path $RepoRoot $OutDir
New-Item -ItemType Directory -Force -Path $OutDirFull | Out-Null

# ── Step 1: Pack the conda environment ───────────────────────────────────────
Step "Packing conda environment '$CondaEnvName' with conda-pack" {
    # --ignore-missing-files: skip .pyc files that may be absent in some envs
    conda-pack -n $CondaEnvName -o $PackedEnvArchive --ignore-missing-files --force
}

Write-Host "Packed archive: $PackedEnvArchive ($([math]::Round((Get-Item $PackedEnvArchive).Length/1MB, 1)) MB)" -ForegroundColor Green

# ── Step 2: Generate NSIS script ─────────────────────────────────────────────
Step "Generating NSIS installer script" {
    $NsisContent = @"
; Offline 3D GIS Desktop — Windows Installer
; Generated by build_windows_installer.ps1
; Uses conda-pack bundle — fully offline, no internet required.

Unicode True
!define APP_NAME      "Offline 3D GIS Desktop"
!define APP_VERSION   "$AppVersion"
!define APP_PUBLISHER "Offline GIS Project"
!define APP_EXE       "offline_gis.exe"
!define INSTALL_DIR   "`$PROGRAMFILES64\OfflineGIS"
!define ENV_SUBDIR    "env"
!define UNINSTALLER   "Uninstall.exe"
!define REG_KEY       "Software\Microsoft\Windows\CurrentVersion\Uninstall\OfflineGIS"

Name "`${APP_NAME} `${APP_VERSION}"
OutFile "$OutDirFull\OfflineGIS_Setup_`${APP_VERSION}.exe"
InstallDir "`${INSTALL_DIR}"
InstallDirRegKey HKLM "`${REG_KEY}" "InstallLocation"
RequestExecutionLevel admin
SetCompressor /SOLID lzma
SetCompressorDictSize 64

!include "MUI2.nsh"
!include "LogicLib.nsh"

; ── Pages ────────────────────────────────────────────────────────────────────
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "$RepoRoot\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ── Installer ────────────────────────────────────────────────────────────────
Section "Main" SEC_MAIN
    SetOutPath "`$INSTDIR"

    ; Unpack the conda-pack archive into env\
    CreateDirectory "`$INSTDIR\`${ENV_SUBDIR}"
    File "$PackedEnvArchive"
    DetailPrint "Unpacking Python environment (this may take a minute)..."
    nsExec::ExecToLog '"cmd.exe" /C "tar -xzf "`$INSTDIR\offline-3d-gis-env.tar.gz"" -C "`$INSTDIR\`${ENV_SUBDIR}""'
    Delete "`$INSTDIR\offline-3d-gis-env.tar.gz"

    ; conda-pack requires running conda-unpack after extraction to fix paths
    DetailPrint "Fixing environment paths..."
    nsExec::ExecToLog '"`$INSTDIR\`${ENV_SUBDIR}\Scripts\conda-unpack.exe"'

    ; Install the app package into the bundled env
    DetailPrint "Installing Offline GIS application..."
    nsExec::ExecToLog '"`$INSTDIR\`${ENV_SUBDIR}\python.exe" -m pip install --no-index --find-links="`$INSTDIR\wheels" offline-3d-gis-app'

    ; Write launcher batch file
    FileOpen `$0 "`$INSTDIR\`${APP_EXE}.cmd" w
    FileWrite `$0 '@echo off\r\n'
    FileWrite `$0 'set QTWEBENGINE_DISABLE_SANDBOX=1\r\n'
    FileWrite `$0 'set NvOptimusEnablement=0x00000001\r\n'
    FileWrite `$0 'set AmdPowerXpressRequestHighPerformance=1\r\n'
    FileWrite `$0 '"`$INSTDIR\`${ENV_SUBDIR}\python.exe" -m offline_gis_app.cli desktop-client %*\r\n'
    FileClose `$0

    ; Write a proper .exe launcher using a VBScript wrapper (no console flash)
    FileOpen `$0 "`$INSTDIR\launch.vbs" w
    FileWrite `$0 'Set WshShell = CreateObject("WScript.Shell")\r\n'
    FileWrite `$0 'WshShell.Run Chr(34) & WScript.ScriptFullName & Chr(34), 0, False\r\n'
    FileClose `$0

    ; Write the actual windowed launcher
    FileOpen `$0 "`$INSTDIR\`${APP_EXE}.cmd" w
    FileWrite `$0 '@echo off\r\n'
    FileWrite `$0 'set QTWEBENGINE_DISABLE_SANDBOX=1\r\n'
    FileWrite `$0 'set NvOptimusEnablement=0x00000001\r\n'
    FileWrite `$0 'set AmdPowerXpressRequestHighPerformance=1\r\n'
    FileWrite `$0 'set QT_OPENGL=angle\r\n'
    FileWrite `$0 'set QT_ANGLE_PLATFORM=d3d11\r\n'
    FileWrite `$0 'start "" "`$INSTDIR\`${ENV_SUBDIR}\pythonw.exe" -m offline_gis_app.cli desktop-client\r\n'
    FileClose `$0

    ; Desktop shortcut
    CreateShortcut "`$DESKTOP\`${APP_NAME}.lnk" "`$INSTDIR\`${APP_EXE}.cmd" "" "`$INSTDIR\`${ENV_SUBDIR}\pythonw.exe" 0

    ; Start menu
    CreateDirectory "`$SMPROGRAMS\`${APP_NAME}"
    CreateShortcut "`$SMPROGRAMS\`${APP_NAME}\`${APP_NAME}.lnk" "`$INSTDIR\`${APP_EXE}.cmd"
    CreateShortcut "`$SMPROGRAMS\`${APP_NAME}\Uninstall.lnk" "`$INSTDIR\`${UNINSTALLER}"

    ; Registry entries for Add/Remove Programs
    WriteRegStr   HKLM "`${REG_KEY}" "DisplayName"      "`${APP_NAME} `${APP_VERSION}"
    WriteRegStr   HKLM "`${REG_KEY}" "DisplayVersion"   "`${APP_VERSION}"
    WriteRegStr   HKLM "`${REG_KEY}" "Publisher"        "`${APP_PUBLISHER}"
    WriteRegStr   HKLM "`${REG_KEY}" "InstallLocation"  "`$INSTDIR"
    WriteRegStr   HKLM "`${REG_KEY}" "UninstallString"  "`$INSTDIR\`${UNINSTALLER}"
    WriteRegDWORD HKLM "`${REG_KEY}" "NoModify"         1
    WriteRegDWORD HKLM "`${REG_KEY}" "NoRepair"         1

    WriteUninstaller "`$INSTDIR\`${UNINSTALLER}"
SectionEnd

; ── Uninstaller ───────────────────────────────────────────────────────────────
Section "Uninstall"
    RMDir /r "`$INSTDIR\`${ENV_SUBDIR}"
    Delete "`$INSTDIR\`${APP_EXE}.cmd"
    Delete "`$INSTDIR\launch.vbs"
    Delete "`$INSTDIR\`${UNINSTALLER}"
    RMDir  "`$INSTDIR"

    Delete "`$DESKTOP\`${APP_NAME}.lnk"
    Delete "`$SMPROGRAMS\`${APP_NAME}\`${APP_NAME}.lnk"
    Delete "`$SMPROGRAMS\`${APP_NAME}\Uninstall.lnk"
    RMDir  "`$SMPROGRAMS\`${APP_NAME}"

    DeleteRegKey HKLM "`${REG_KEY}"
SectionEnd
"@
    Set-Content -Path $NsisScript -Value $NsisContent -Encoding UTF8
}

# ── Step 3: Build wheels for offline pip install ──────────────────────────────
$WheelsDir = Join-Path $RepoRoot "installer\wheels"
Step "Building app wheel for offline installation" {
    New-Item -ItemType Directory -Force -Path $WheelsDir | Out-Null
    conda run -n $CondaEnvName python -m pip wheel . --no-deps -w $WheelsDir
}

# ── Step 4: Compile NSIS installer ───────────────────────────────────────────
Step "Compiling NSIS installer" {
    makensis $NsisScript
}

$InstallerPath = Join-Path $OutDirFull "OfflineGIS_Setup_$AppVersion.exe"
if (Test-Path $InstallerPath) {
    $SizeMB = [math]::Round((Get-Item $InstallerPath).Length / 1MB, 1)
    Write-Host "`nInstaller built: $InstallerPath ($SizeMB MB)" -ForegroundColor Green
} else {
    throw "Installer not found at expected path: $InstallerPath"
}

Write-Host @"

Build complete.
  Installer : $InstallerPath
  Version   : $AppVersion

To install on a Windows machine (no internet required):
  1. Copy OfflineGIS_Setup_$AppVersion.exe to the target machine
  2. Run as Administrator
  3. Launch from Desktop shortcut or Start Menu

GPU notes:
  - NVIDIA Optimus: NvOptimusEnablement=1 forces discrete GPU
  - AMD switchable: AmdPowerXpressRequestHighPerformance=1
  - Qt WebEngine uses ANGLE/D3D11 for hardware-accelerated WebGL (Cesium 3D)
"@ -ForegroundColor Green
